name: Deploy Site

on:
  - push
  - pull_request

permissions:
  contents: read
  packages: read

jobs:
  run-super-linter:
    name: Run GitHub Super Linter
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BIOME_FORMAT: "false"
